import 'package:parlo/Model/Data_Cass.dart';

List<model> clothes = [
  model(
    image: 'assets/Images/clothes_icons/clothes/01_tshirt.png',
    textenglish: 'T-Shirt',
    texItliano: 'Maglietta',
    audio: 'Audies/Clothes1_words/27_maglietta.mp3',
  ),
  model(
    image: 'assets/Images/clothes_icons/clothes/02_shirt.png',
    textenglish: 'Shirt',
    texItliano: 'Camicia',
    audio: 'Audies/Clothes1_words/26_camicia.mp3',
  ),
  model(
    image: 'assets/Images/clothes_icons/clothes/03_jacket.png',
    textenglish: 'Jacket',
    texItliano: 'Giacca',
    audio: 'Audies/Clothes1_words/08_giacca.mp3',
  ),
  model(
    image: 'assets/Images/clothes_icons/clothes/04_coat.png',
    textenglish: 'Coat',
    texItliano: 'Cappotto',
    audio: 'Audies/Clothes1_words/07_cappotto.mp3',
  ),
  model(
    image: 'assets/Images/clothes_icons/clothes/05_jeans.png',
    textenglish: 'Jeans',
    texItliano: 'Jeans',
    audio: 'Audies/Clothes1_words/02_jeans.mp3',
  ),
  model(
    image: 'assets/Images/clothes_icons/clothes/06_dress.png',
    textenglish: 'Dress',
    texItliano: 'Vestito',
    audio: 'Audies/Clothes1_words/15_vestito.mp3',
  ),
  model(
    image: 'assets/Images/clothes_icons/clothes/07_skirt.png',
    textenglish: 'Skirt',
    texItliano: 'Gonna',
    audio: 'Audies/Clothes1_words/06_gonna.mp3',
  ),
  model(
    image: 'assets/Images/clothes_icons/clothes/08_suit.png',
    textenglish: 'Suit',
    texItliano: 'Abito',
    audio: 'Audies/Clothes1_words/24_completo.mp3',
  ),
  model(
    image: 'assets/Images/clothes_icons/clothes/09_shoe.png',
    textenglish: 'Shoe',
    texItliano: 'Scarpa',
    audio: 'Audies/Clothes1_words/28_scarpa.mp3',
  ),
  model(
    image: 'assets/Images/clothes_icons/clothes/10_sneaker.png',
    textenglish: 'Sneaker',
    texItliano: 'Scarpa da ginnastica',
    audio: 'Audies/Clothes1_words/21_sneaker.mp3',
  ),
  model(
    image: 'assets/Images/clothes_icons/clothes/11_boot.png',
    textenglish: 'Boot',
    texItliano: 'Stivale',
    audio: 'Audies/Clothes1_words/12_stivale.mp3',
  ),
  model(
    image: 'assets/Images/clothes_icons/clothes/12_high_heel.png',
    textenglish: 'High Heel',
    texItliano: 'Tacco alto',
    audio: 'Audies/Clothes1_words/05_scarpa_con_tacco_alto.mp3',
  ),
  model(
    image: 'assets/Images/clothes_icons/clothes/13_sandal.png',
    textenglish: 'Sandal',
    texItliano: 'Sandalo',
    audio: 'Audies/Clothes1_words/16_sandalo.mp3',
  ),
  model(
    image: 'assets/Images/clothes_icons/clothes/14_sock.png',
    textenglish: 'Sock',
    texItliano: 'Calzino',
    audio: 'Audies/Clothes1_words/22_calzino.mp3',
  ),
  model(
    image: 'assets/Images/clothes_icons/clothes/15_hat.png',
    textenglish: 'Hat',
    texItliano: 'Cappello',
    audio: 'Audies/Clothes1_words/01_cappello.mp3',
  ),
  model(
    image: 'assets/Images/clothes_icons/clothes/16_cap.png',
    textenglish: 'Cap',
    texItliano: 'Berretto',
    audio: 'Audies/Clothes1_words/25_berretto.mp3',
  ),
  model(
    image: 'assets/Images/clothes_icons/clothes/17_scarf.png',
    textenglish: 'Scarf',
    texItliano: 'Sciarpa',
    audio: 'Audies/Clothes1_words/18_sciarpa.mp3',
  ),
  model(
    image: 'assets/Images/clothes_icons/clothes/18_gloves.png',
    textenglish: 'Gloves',
    texItliano: 'Guanti',
    audio: 'Audies/Clothes1_words/14_guanti.mp3',
  ),
  model(
    image: 'assets/Images/clothes_icons/clothes/19_glasses.png',
    textenglish: 'Glasses',
    texItliano: 'Occhiali',
    audio: 'Audies/Clothes1_words/13_occhiali.mp3',
  ),
  model(
    image: 'assets/Images/clothes_icons/clothes/20_sunglasses.png',
    textenglish: 'Sunglasses',
    texItliano: 'Occhiali da sole',
    audio: 'Audies/Clothes1_words/17_occhiali_da_sole.mp3',
  ),
  model(
    image: 'assets/Images/clothes_icons/clothes/21_bag.png',
    textenglish: 'Bag',
    texItliano: 'Borsa',
    audio: 'Audies/Clothes1_words/20_borsa.mp3',
  ),
  model(
    image: 'assets/Images/clothes_icons/clothes/22_backpack.png',
    textenglish: 'Backpack',
    texItliano: 'Zaino',
    audio: 'Audies/Clothes1_words/19_zaino.mp3',
  ),
  model(
    image: 'assets/Images/clothes_icons/clothes/23_watch.png',
    textenglish: 'Watch',
    texItliano: 'Orologio',
    audio: 'Audies/Clothes1_words/23_orologio.mp3',
  ),
  model(
    image: 'assets/Images/clothes_icons/clothes/24_ring.png',
    textenglish: 'Ring',
    texItliano: 'Anello',
    audio: 'Audies/Clothes1_words/10_anello.mp3',
  ),
  model(
    image: 'assets/Images/clothes_icons/clothes/25_crown.png',
    textenglish: 'Crown',
    texItliano: 'Corona',
    audio: 'Audies/Clothes1_words/09_corona.mp3',
  ),
  model(
    image: 'assets/Images/clothes_icons/clothes/26_tie.png',
    textenglish: 'Tie',
    texItliano: 'Cravatta',
    audio: 'Audies/Clothes1_words/03_cravatta.mp3',
  ),
  model(
    image: 'assets/Images/clothes_icons/clothes/27_bikini.png',
    textenglish: 'Bikini',
    texItliano: 'Bikini',
    audio: 'Audies/Clothes1_words/04_bikini.mp3',
  ),
  model(
    image: 'assets/Images/clothes_icons/clothes/28_kimono.png',
    textenglish: 'Kimono',
    texItliano: 'Kimono',
    audio: 'Audies/Clothes1_words/11_kimono.mp3',
  ),
];
