import 'package:parlo/Model/Data_Cass.dart';

List<model> house = [
  model(
    image: 'assets/Images/house_icons/house/01_house.png',
    textenglish: 'House',
    texItliano: 'Casa',
    audio: 'Audies/House1_words/01_casa.mp3',
  ),
  model(
    image: 'assets/Images/house_icons/house/02_bed.png',
    textenglish: 'Bed',
    texItliano: 'Letto',
    audio: 'Audies/House1_words/02_letto.mp3',
  ),
  model(
    image: 'assets/Images/house_icons/house/03_couch.png',
    textenglish: 'Couch',
    texItliano: 'Divano',
    audio: 'Audies/House1_words/16_divano.mp3',
  ),
  model(
    image: 'assets/Images/house_icons/house/04_chair.png',
    textenglish: 'Chair',
    texItliano: 'Sedia',
    audio: 'Audies/House1_words/17_sedia.mp3',
  ),
  model(
    image: 'assets/Images/house_icons/house/05_bathtub.png',
    textenglish: 'Bathtub',
    texItliano: 'Vasca da bagno',
    audio: 'Audies/House1_words/24_vasca_da_bagno.mp3',
  ),
  model(
    image: 'assets/Images/house_icons/house/06_shower.png',
    textenglish: 'Shower',
    texItliano: 'Doccia',
    audio: 'Audies/House1_words/07_doccia.mp3',
  ),
  model(
    image: 'assets/Images/house_icons/house/07_toilet.png',
    textenglish: 'Toilet',
    texItliano: 'Toilette',
    audio: 'Audies/House1_words/20_WC.mp3',
  ),
  model(
    image: 'assets/Images/house_icons/house/08_door.png',
    textenglish: 'Door',
    texItliano: 'Porta',
    audio: 'Audies/House1_words/03_porta.mp3',
  ),
  model(
    image: 'assets/Images/house_icons/house/09_window.png',
    textenglish: 'Window',
    texItliano: 'Finestra',
    audio: 'Audies/House1_words/26_finestra.mp3',
  ),
  model(
    image: 'assets/Images/house_icons/house/10_mirror.png',
    textenglish: 'Mirror',
    texItliano: 'Specchio',
    audio: 'Audies/House1_words/27_specchio.mp3',
  ),
  model(
    image: 'assets/Images/house_icons/house/11_lamp.png',
    textenglish: 'Lamp',
    texItliano: 'Lampada',
    audio: 'Audies/House1_words/22_lampada.mp3',
  ),
  model(
    image: 'assets/Images/house_icons/house/12_candle.png',
    textenglish: 'Candle',
    texItliano: 'Candela',
    audio: 'Audies/House1_words/05_candela.mp3',
  ),
  model(
    image: 'assets/Images/house_icons/house/13_clock.png',
    textenglish: 'Clock',
    texItliano: 'Orologio',
    audio: 'Audies/House1_words/08_orologio.mp3',
  ),
  model(
    image: 'assets/Images/house_icons/house/14_fridge.png',
    textenglish: 'Fridge',
    texItliano: 'Frigorifero',
    audio: 'Audies/House1_words/25_frigorifero.mp3',
  ),
  model(
    image: 'assets/Images/house_icons/house/15_tv.png',
    textenglish: 'TV',
    texItliano: 'Televisione',
    audio: 'Audies/House1_words/13_TV.mp3',
  ),
  model(
    image: 'assets/Images/house_icons/house/16_laundry_basket.png',
    textenglish: 'Laundry Basket',
    texItliano: 'Cesto della biancheria',
    audio: 'Audies/House1_words/04_cesto_della_biancheria.mp3',
  ),
  model(
    image: 'assets/Images/house_icons/house/17_hand_fan.png',
    textenglish: 'Hand Fan',
    texItliano: 'Ventaglio',
    audio: 'Audies/House1_words/06_ventilconio.mp3',
  ),
  model(
    image: 'assets/Images/house_icons/house/18_key.png',
    textenglish: 'Key',
    texItliano: 'Chiave',
    audio: 'Audies/House1_words/09_chiave.mp3',
  ),
  model(
    image: 'assets/Images/house_icons/house/19_hammer.png',
    textenglish: 'Hammer',
    texItliano: 'Martello',
    audio: 'Audies/House1_words/21_martello.mp3',
  ),
  model(
    image: 'assets/Images/house_icons/house/20_broom.png',
    textenglish: 'Broom',
    texItliano: 'Scopa',
    audio: 'Audies/House1_words/10_scopa.mp3',
  ),
  model(
    image: 'assets/Images/house_icons/house/21_bucket.png',
    textenglish: 'Bucket',
    texItliano: 'Secchio',
    audio: 'Audies/House1_words/19_secchio.mp3',
  ),
  model(
    image: 'assets/Images/house_icons/house/22_toothbrush.png',
    textenglish: 'Toothbrush',
    texItliano: 'Spazzolino',
    audio: 'Audies/House1_words/23_spazzolino_da_denti.mp3',
  ),
  model(
    image: 'assets/Images/house_icons/house/23_soap.png',
    textenglish: 'Soap',
    texItliano: 'Sapone',
    audio: 'Audies/House1_words/14_sapone.mp3',
  ),
  model(
    image: 'assets/Images/house_icons/house/24_towel.png',
    textenglish: 'Towel',
    texItliano: 'Asciugamano',
    audio: 'Audies/House1_words/18_asciugamano.mp3',
  ),
  model(
    image: 'assets/Images/house_icons/house/25_plant.png',
    textenglish: 'Plant',
    texItliano: 'Pianta',
    audio: 'Audies/House1_words/15_pianta.mp3',
  ),
  model(
    image: 'assets/Images/house_icons/house/26_picture_frame.png',
    textenglish: 'Picture Frame',
    texItliano: 'Cornice',
    audio: 'Audies/House1_words/11_cornice.mp3',
  ),
  model(
    image: 'assets/Images/house_icons/house/27_gift.png',
    textenglish: 'Gift',
    texItliano: 'Regalo',
    audio: 'Audies/House1_words/12_regalo.mp3',
  ),
  model(
    image: 'assets/Images/house_icons/house/28_bell.png',
    textenglish: 'Bell',
    texItliano: 'Campanello',
    audio: 'Audies/House1_words/28_campanello.mp3',
  ),
];
