
import 'package:parlo/Model/Data_Cass.dart';

List<model> numbers = [
  model(
    image: 'assets/Images/numbers_order/numbers/1.png',
    textenglish: 'One',
    texItliano: 'Uno',
    audio: 'Audies/Numbers_words/001.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/2.png',
    textenglish: 'Two',
    texItliano: 'Due',
    audio: 'Audies/Numbers_words/002.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/3.png',
    textenglish: 'Three',
    texItliano: 'Tre',
    audio: 'Audies/Numbers_words/003.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/4.png',
    textenglish: 'Four',
    texItliano: 'Quattro',
    audio: 'Audies/Numbers_words/004.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/5.png',
    textenglish: 'Five',
    texItliano: 'Cinque',
    audio: 'Audies/Numbers_words/005.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/6.png',
    textenglish: 'Six',
    texItliano: 'Sei',
    audio: 'Audies/Numbers_words/006.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/7.png',
    textenglish: 'Seven',
    texItliano: 'Sette',
    audio: 'Audies/Numbers_words/007.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/8.png',
    textenglish: 'Eight',
    texItliano: 'Otto',
    audio: 'Audies/Numbers_words/008.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/9.png',
    textenglish: 'Nine',
    texItliano: 'Nove',
    audio: 'Audies/Numbers_words/009.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/10.png',
    textenglish: 'Ten',
    texItliano: 'Dieci',
    audio: 'Audies/Numbers_words/010.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/11.png',
    textenglish: 'Eleven',
    texItliano: 'Undici',
    audio: 'Audies/Numbers_words/011.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/12.png',
    textenglish: 'Twelve',
    texItliano: 'Dodici',
    audio: 'Audies/Numbers_words/012.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/13.png',
    textenglish: 'Thirteen',
    texItliano: 'Tredici',
    audio: 'Audies/Numbers_words/013.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/14.png',
    textenglish: 'Fourteen',
    texItliano: 'Quattordici',
    audio: 'Audies/Numbers_words/014.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/15.png',
    textenglish: 'Fifteen',
    texItliano: 'Quindici',
    audio: 'Audies/Numbers_words/015.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/16.png',
    textenglish: 'Sixteen',
    texItliano: 'Sedici',
    audio: 'Audies/Numbers_words/016.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/17.png',
    textenglish: 'Seventeen',
    texItliano: 'Diciassette',
    audio: 'Audies/Numbers_words/017.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/18.png',
    textenglish: 'Eighteen',
    texItliano: 'Diciotto',
    audio: 'Audies/Numbers_words/018.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/19.png',
    textenglish: 'Nineteen',
    texItliano: 'Diciannove',
    audio: 'Audies/Numbers_words/019.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/20.png',
    textenglish: 'Twenty',
    texItliano: 'Venti',
    audio: 'Audies/Numbers_words/020.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/21.png',
    textenglish: 'Twenty-One',
    texItliano: 'Ventuno',
    audio: 'Audies/Numbers_words/021.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/22.png',
    textenglish: 'Twenty-Two',
    texItliano: 'Ventidue',
    audio: 'Audies/Numbers_words/022.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/23.png',
    textenglish: 'Twenty-Three',
    texItliano: 'Ventitré',
    audio: 'Audies/Numbers_words/023.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/24.png',
    textenglish: 'Twenty-Four',
    texItliano: 'Ventiquattro',
    audio: 'Audies/Numbers_words/024.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/25.png',
    textenglish: 'Twenty-Five',
    texItliano: 'Venticinque',
    audio: 'Audies/Numbers_words/025.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/26.png',
    textenglish: 'Twenty-Six',
    texItliano: 'Ventisei',
    audio: 'Audies/Numbers_words/026.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/27.png',
    textenglish: 'Twenty-Seven',
    texItliano: 'Ventisette',
    audio: 'Audies/Numbers_words/027.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/28.png',
    textenglish: 'Twenty-Eight',
    texItliano: 'Ventotto',
    audio: 'Audies/Numbers_words/028.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/29.png',
    textenglish: 'Twenty-Nine',
    texItliano: 'Ventinove',
    audio: 'Audies/Numbers_words/029.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/30.png',
    textenglish: 'Thirty',
    texItliano: 'Trenta',
    audio: 'Audies/Numbers_words/030.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/31.png',
    textenglish: 'Thirty-One',
    texItliano: 'Trentuno',
    audio: 'Audies/Numbers_words/031.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/32.png',
    textenglish: 'Thirty-Two',
    texItliano: 'Trentadue',
    audio: 'Audies/Numbers_words/032.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/33.png',
    textenglish: 'Thirty-Three',
    texItliano: 'Trentatré',
    audio: 'Audies/Numbers_words/033.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/34.png',
    textenglish: 'Thirty-Four',
    texItliano: 'Trentaquattro',
    audio: 'Audies/Numbers_words/034.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/35.png',
    textenglish: 'Thirty-Five',
    texItliano: 'Trentacinque',
    audio: 'Audies/Numbers_words/035.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/36.png',
    textenglish: 'Thirty-Six',
    texItliano: 'Trentasei',
    audio: 'Audies/Numbers_words/036.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/37.png',
    textenglish: 'Thirty-Seven',
    texItliano: 'Trentasette',
    audio: 'Audies/Numbers_words/037.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/38.png',
    textenglish: 'Thirty-Eight',
    texItliano: 'Trentotto',
    audio: 'Audies/Numbers_words/038.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/39.png',
    textenglish: 'Thirty-Nine',
    texItliano: 'Trentanove',
    audio: 'Audies/Numbers_words/039.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/40.png',
    textenglish: 'Forty',
    texItliano: 'Quaranta',
    audio: 'Audies/Numbers_words/040.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/41.png',
    textenglish: 'Forty-One',
    texItliano: 'Quarantuno',
    audio: 'Audies/Numbers_words/041.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/42.png',
    textenglish: 'Forty-Two',
    texItliano: 'Quarantadue',
    audio: 'Audies/Numbers_words/042.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/43.png',
    textenglish: 'Forty-Three',
    texItliano: 'Quarantatré',
    audio: 'Audies/Numbers_words/043.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/44.png',
    textenglish: 'Forty-Four',
    texItliano: 'Quarantaquattro',
    audio: 'Audies/Numbers_words/044.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/45.png',
    textenglish: 'Forty-Five',
    texItliano: 'Quarantacinque',
    audio: 'Audies/Numbers_words/045.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/46.png',
    textenglish: 'Forty-Six',
    texItliano: 'Quarantasei',
    audio: 'Audies/Numbers_words/046.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/47.png',
    textenglish: 'Forty-Seven',
    texItliano: 'Quarantasette',
    audio: 'Audies/Numbers_words/047.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/48.png',
    textenglish: 'Forty-Eight',
    texItliano: 'Quarantotto',
    audio: 'Audies/Numbers_words/048.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/49.png',
    textenglish: 'Forty-Nine',
    texItliano: 'Quarantanove',
    audio: 'Audies/Numbers_words/049.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/50.png',
    textenglish: 'Fifty',
    texItliano: 'Cinquanta',
    audio: 'Audies/Numbers_words/050.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/51.png',
    textenglish: 'Fifty-One',
    texItliano: 'Cinquantuno',
    audio: 'Audies/Numbers_words/051.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/52.png',
    textenglish: 'Fifty-Two',
    texItliano: 'Cinquantadue',
    audio: 'Audies/Numbers_words/052.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/53.png',
    textenglish: 'Fifty-Three',
    texItliano: 'Cinquantatré',
    audio: 'Audies/Numbers_words/053.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/54.png',
    textenglish: 'Fifty-Four',
    texItliano: 'Cinquantaquattro',
    audio: 'Audies/Numbers_words/054.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/55.png',
    textenglish: 'Fifty-Five',
    texItliano: 'Cinquantacinque',
    audio: 'Audies/Numbers_words/055.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/56.png',
    textenglish: 'Fifty-Six',
    texItliano: 'Cinquantasei',
    audio: 'Audies/Numbers_words/056.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/57.png',
    textenglish: 'Fifty-Seven',
    texItliano: 'Cinquantasette',
    audio: 'Audies/Numbers_words/057.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/58.png',
    textenglish: 'Fifty-Eight',
    texItliano: 'Cinquantotto',
    audio: 'Audies/Numbers_words/058.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/59.png',
    textenglish: 'Fifty-Nine',
    texItliano: 'Cinquantanove',
    audio: 'Audies/Numbers_words/059.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/60.png',
    textenglish: 'Sixty',
    texItliano: 'Sessanta',
    audio: 'Audies/Numbers_words/060.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/61.png',
    textenglish: 'Sixty-One',
    texItliano: 'Sessantuno',
    audio: 'Audies/Numbers_words/061.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/62.png',
    textenglish: 'Sixty-Two',
    texItliano: 'Sessantadue',
    audio: 'Audies/Numbers_words/062.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/63.png',
    textenglish: 'Sixty-Three',
    texItliano: 'Sessantatré',
    audio: 'Audies/Numbers_words/063.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/64.png',
    textenglish: 'Sixty-Four',
    texItliano: 'Sessantaquattro',
    audio: 'Audies/Numbers_words/064.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/65.png',
    textenglish: 'Sixty-Five',
    texItliano: 'Sessantacinque',
    audio: 'Audies/Numbers_words/065.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/66.png',
    textenglish: 'Sixty-Six',
    texItliano: 'Sessantasei',
    audio: 'Audies/Numbers_words/066.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/67.png',
    textenglish: 'Sixty-Seven',
    texItliano: 'Sessantasette',
    audio: 'Audies/Numbers_words/067.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/68.png',
    textenglish: 'Sixty-Eight',
    texItliano: 'Sessantotto',
    audio: 'Audies/Numbers_words/068.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/69.png',
    textenglish: 'Sixty-Nine',
    texItliano: 'Sessantanove',
    audio: 'Audies/Numbers_words/069.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/70.png',
    textenglish: 'Seventy',
    texItliano: 'Settanta',
    audio: 'Audies/Numbers_words/070.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/71.png',
    textenglish: 'Seventy-One',
    texItliano: 'Settantuno',
    audio: 'Audies/Numbers_words/071.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/72.png',
    textenglish: 'Seventy-Two',
    texItliano: 'Settantadue',
    audio: 'Audies/Numbers_words/072.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/73.png',
    textenglish: 'Seventy-Three',
    texItliano: 'Settantatré',
    audio: 'Audies/Numbers_words/073.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/74.png',
    textenglish: 'Seventy-Four',
    texItliano: 'Settantaquattro',
    audio: 'Audies/Numbers_words/074.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/75.png',
    textenglish: 'Seventy-Five',
    texItliano: 'Settantacinque',
    audio: 'Audies/Numbers_words/075.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/76.png',
    textenglish: 'Seventy-Six',
    texItliano: 'Settantasei',
    audio: 'Audies/Numbers_words/076.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/77.png',
    textenglish: 'Seventy-Seven',
    texItliano: 'Settantasette',
    audio: 'Audies/Numbers_words/077.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/78.png',
    textenglish: 'Seventy-Eight',
    texItliano: 'Settantotto',
    audio: 'Audies/Numbers_words/078.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/79.png',
    textenglish: 'Seventy-Nine',
    texItliano: 'Settantanove',
    audio: 'Audies/Numbers_words/079.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/80.png',
    textenglish: 'Eighty',
    texItliano: 'Ottanta',
    audio: 'Audies/Numbers_words/080.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/81.png',
    textenglish: 'Eighty-One',
    texItliano: 'Ottantuno',
    audio: 'Audies/Numbers_words/081.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/82.png',
    textenglish: 'Eighty-Two',
    texItliano: 'Ottantadue',
    audio: 'Audies/Numbers_words/082.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/83.png',
    textenglish: 'Eighty-Three',
    texItliano: 'Ottantatré',
    audio: 'Audies/Numbers_words/083.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/84.png',
    textenglish: 'Eighty-Four',
    texItliano: 'Ottantaquattro',
    audio: 'Audies/Numbers_words/084.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/85.png',
    textenglish: 'Eighty-Five',
    texItliano: 'Ottantacinque',
    audio: 'Audies/Numbers_words/085.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/86.png',
    textenglish: 'Eighty-Six',
    texItliano: 'Ottantasei',
    audio: 'Audies/Numbers_words/086.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/87.png',
    textenglish: 'Eighty-Seven',
    texItliano: 'Ottantasette',
    audio: 'Audies/Numbers_words/087.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/88.png',
    textenglish: 'Eighty-Eight',
    texItliano: 'Ottantotto',
    audio: 'Audies/Numbers_words/088.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/89.png',
    textenglish: 'Eighty-Nine',
    texItliano: 'Ottantanove',
    audio: 'Audies/Numbers_words/089.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/90.png',
    textenglish: 'Ninety',
    texItliano: 'Novanta',
    audio: 'Audies/Numbers_words/090.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/91.png',
    textenglish: 'Ninety-One',
    texItliano: 'Novantuno',
    audio: 'Audies/Numbers_words/091.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/92.png',
    textenglish: 'Ninety-Two',
    texItliano: 'Novantadue',
    audio: 'Audies/Numbers_words/092.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/93.png',
    textenglish: 'Ninety-Three',
    texItliano: 'Novantatré',
    audio: 'Audies/Numbers_words/093.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/94.png',
    textenglish: 'Ninety-Four',
    texItliano: 'Novantaquattro',
    audio: 'Audies/Numbers_words/094.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/95.png',
    textenglish: 'Ninety-Five',
    texItliano: 'Novantacinque',
    audio: 'Audies/Numbers_words/095.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/96.png',
    textenglish: 'Ninety-Six',
    texItliano: 'Novantasei',
    audio: 'Audies/Numbers_words/096.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/97.png',
    textenglish: 'Ninety-Seven',
    texItliano: 'Novantasette',
    audio: 'Audies/Numbers_words/097.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/98.png',
    textenglish: 'Ninety-Eight',
    texItliano: 'Novantotto',
    audio: 'Audies/Numbers_words/098.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/99.png',
    textenglish: 'Ninety-Nine',
    texItliano: 'Novantanove',
    audio: 'Audies/Numbers_words/099.mp3',
  ),
  model(
    image: 'assets/Images/numbers_order/numbers/100.png',
    textenglish: 'One Hundred',
    texItliano: 'Cento',
    audio: 'Audies/Numbers_words/100.mp3',
  ),
];