import 'package:parlo/Model/Data_Cass.dart';

List<model> school = [
  model(
    image: 'assets/Images/school_icons/school/01_school_building.png',
    textenglish: 'School',
    texItliano: 'Scuola',
    audio: 'Audies/School1_words/01_edificio_scolastico.mp3',
  ),
  model(
    image: 'assets/Images/school_icons/school/02_backpack.png',
    textenglish: 'Backpack',
    texItliano: 'Zaino',
    audio: 'Audies/School1_words/02_zaino.mp3',
  ),
  model(
    image: 'assets/Images/school_icons/school/03_book.png',
    textenglish: 'Book',
    texItliano: 'Libro',
    audio: 'Audies/School1_words/03_libro.mp3',
  ),
  model(
    image: 'assets/Images/school_icons/school/04_books.png',
    textenglish: 'Books',
    texItliano: 'Libri',
    audio: 'Audies/School1_words/04_libri.mp3',
  ),
  model(
    image: 'assets/Images/school_icons/school/05_notebook.png',
    textenglish: 'Notebook',
    texItliano: 'Quaderno',
    audio: 'Audies/School1_words/05_quaderno.mp3',
  ),
  model(
    image: 'assets/Images/school_icons/school/06_pencil.png',
    textenglish: 'Pencil',
    texItliano: 'Matita',
    audio: 'Audies/School1_words/06_matita.mp3',
  ),
  model(
    image: 'assets/Images/school_icons/school/07_pen.png',
    textenglish: 'Pen',
    texItliano: 'Penna',
    audio: 'Audies/School1_words/08_penna.mp3',
  ),
  model(
    image: 'assets/Images/school_icons/school/08_crayon.png',
    textenglish: 'Crayon',
    texItliano: 'Pastello',
    audio: 'Audies/School1_words/07_pastello.mp3',
  ),
  model(
    image: 'assets/Images/school_icons/school/09_ruler.png',
    textenglish: 'Ruler',
    texItliano: 'Righello',
    audio: 'Audies/School1_words/09_righello.mp3',
  ),
  model(
    image: 'assets/Images/school_icons/school/10_triangle_ruler.png',
    textenglish: 'Set Square',
    texItliano: 'Squadra',
    audio: 'Audies/School1_words/10_righello_triangolare.mp3',
  ),
  model(
    image: 'assets/Images/school_icons/school/11_scissors.png',
    textenglish: 'Scissors',
    texItliano: 'Forbici',
    audio: 'Audies/School1_words/11_forbici.mp3',
  ),
  model(
    image: 'assets/Images/school_icons/school/12_clipboard.png',
    textenglish: 'Clipboard',
    texItliano: 'Clipboard',
    audio: 'Audies/School1_words/12_appunti.mp3',
  ),
  model(
    image: 'assets/Images/school_icons/school/13_paperclip.png',
    textenglish: 'Paperclip',
    texItliano: 'Graffetta',
    audio: 'Audies/School1_words/13_graffetta.mp3',
  ),
  model(
    image: 'assets/Images/school_icons/school/14_pushpin.png',
    textenglish: 'Pushpin',
    texItliano: 'Puntina',
    audio: 'Audies/School1_words/14_puntina_da_disegno.mp3',
  ),
  model(
    image: 'assets/Images/school_icons/school/15_calculator.png',
    textenglish: 'Calculator',
    texItliano: 'Calcolatrice',
    audio: 'Audies/School1_words/15_calcolatrice.mp3',
  ),
  model(
    image: 'assets/Images/school_icons/school/16_globe.png',
    textenglish: 'Globe',
    texItliano: 'Globo',
    audio: 'Audies/School1_words/16_mappamondo.mp3',
  ),
  model(
    image: 'assets/Images/school_icons/school/17_microscope.png',
    textenglish: 'Microscope',
    texItliano: 'Microscopio',
    audio: 'Audies/School1_words/17_microscopio.mp3',
  ),
  model(
    image: 'assets/Images/school_icons/school/18_telescope.png',
    textenglish: 'Telescope',
    texItliano: 'Telescopio',
    audio: 'Audies/School1_words/18_telescopio.mp3',
  ),
  model(
    image: 'assets/Images/school_icons/school/19_chart.png',
    textenglish: 'Chart',
    texItliano: 'Grafico',
    audio: 'Audies/School1_words/19_grafico.mp3',
  ),
  model(
    image: 'assets/Images/school_icons/school/20_graduation_cap.png',
    textenglish: 'Graduation Cap',
    texItliano: 'Tocco',
    audio: 'Audies/School1_words/20_cappello_di_laurea.mp3',
  ),
  model(
    image: 'assets/Images/school_icons/school/21_bell.png',
    textenglish: 'Bell',
    texItliano: 'Campanella',
    audio: 'Audies/School1_words/21_campanulare.mp3',
  ),
  model(
    image: 'assets/Images/school_icons/school/22_desk.png',
    textenglish: 'Desk',
    texItliano: 'Banco',
    audio: 'Audies/School1_words/22_scrivania.mp3',
  ),
  model(
    image: 'assets/Images/school_icons/school/23_laptop.png',
    textenglish: 'Laptop',
    texItliano: 'Portatile',
    audio: 'Audies/School1_words/23_computer_portatile.mp3',
  ),
  model(
    image: 'assets/Images/school_icons/school/24_computer.png',
    textenglish: 'Computer',
    texItliano: 'Computer',
    audio: 'Audies/School1_words/24_computer.mp3',
  ),
  model(
    image: 'assets/Images/school_icons/school/25_test_paper.png',
    textenglish: 'Test Paper',
    texItliano: 'Foglio d’esame',
    audio: 'Audies/School1_words/25_test_di_verifica.mp3',
  ),
  model(
    image: 'assets/Images/school_icons/school/26_medal.png',
    textenglish: 'Medal',
    texItliano: 'Medaglia',
    audio: 'Audies/School1_words/26_medaglia.mp3',
  ),
  model(
    image: 'assets/Images/school_icons/school/27_trophy.png',
    textenglish: 'Trophy',
    texItliano: 'Trofeo',
    audio: 'Audies/School1_words/27_trofeo.mp3',
  ),
  model(
    image: 'assets/Images/school_icons/school/28_art_palette.png',
    textenglish: 'Art Palette',
    texItliano: 'Tavolozza',
    audio: "Audies/School1_words/28_tavolozza_d'arte.mp3",
  ),
];
