import 'package:parlo/Model/Data_Cass.dart';

List<model> transport = [
  model(
    image: 'assets/Images/transport_icons/transport/01_car.png',
    textenglish: 'Car',
    texItliano: 'Auto',
    audio: 'Audies/Transsport_words/01_auto.mp3',
  ),
  model(
    image: 'assets/Images/transport_icons/transport/02_taxi.png',
    textenglish: 'Taxi',
    texItliano: 'Taxi',
    audio: 'Audies/Transsport_words/02_taxi.mp3',
  ),
  model(
    image: 'assets/Images/transport_icons/transport/03_bus.png',
    textenglish: 'Bus',
    texItliano: 'Autobus',
    audio: 'Audies/Transsport_words/03_autobus.mp3',
  ),
  model(
    image: 'assets/Images/transport_icons/transport/04_truck.png',
    textenglish: 'Truck',
    texItliano: 'Camion',
    audio: 'Audies/Transsport_words/04_camion.mp3',
  ),
  model(
    image: 'assets/Images/transport_icons/transport/05_police_car.png',
    textenglish: 'Police Car',
    texItliano: 'Auto della polizia',
    audio: 'Audies/Transsport_words/05_auto_della_polizia.mp3',
  ),
  model(
    image: 'assets/Images/transport_icons/transport/06_ambulance.png',
    textenglish: 'Ambulance',
    texItliano: 'Ambulanza',
    audio: 'Audies/Transsport_words/06_ambulanza.mp3',
  ),
  model(
    image: 'assets/Images/transport_icons/transport/07_fire_truck.png',
    textenglish: 'Fire Truck',
    texItliano: 'Camion dei pompieri',
    audio: 'Audies/Transsport_words/07_autopompa.mp3',
  ),
  model(
    image: 'assets/Images/transport_icons/transport/08_motorcycle.png',
    textenglish: 'Motorcycle',
    texItliano: 'Motocicletta',
    audio: 'Audies/Transsport_words/08_motocicletta.mp3',
  ),
  model(
    image: 'assets/Images/transport_icons/transport/09_bicycle.png',
    textenglish: 'Bicycle',
    texItliano: 'Bicicletta',
    audio: 'Audies/Transsport_words/09_bicicletta.mp3',
  ),
  model(
    image: 'assets/Images/transport_icons/transport/10_tuk_tuk.png',
    textenglish: 'Tuk Tuk',
    texItliano: 'Tuk Tuk',
    audio: 'Audies/Transsport_words/10_tuk-tuk.mp3',
  ),
  model(
    image: 'assets/Images/transport_icons/transport/11_train.png',
    textenglish: 'Train',
    texItliano: 'Treno',
    audio: 'Audies/Transsport_words/11_treno.mp3',
  ),
  model(
    image: 'assets/Images/transport_icons/transport/12_metro.png',
    textenglish: 'Metro',
    texItliano: 'Metropolitana',
    audio: 'Audies/Transsport_words/12_metropolitana.mp3',
  ),
  model(
    image: 'assets/Images/transport_icons/transport/13_tram.png',
    textenglish: 'Tram',
    texItliano: 'Tram',
    audio: 'Audies/Transsport_words/13_tram.mp3',
  ),
  model(
    image: 'assets/Images/transport_icons/transport/14_airplane.png',
    textenglish: 'Airplane',
    texItliano: 'Aereo',
    audio: 'Audies/Transsport_words/14_aereo.mp3',
  ),
  model(
    image: 'assets/Images/transport_icons/transport/15_helicopter.png',
    textenglish: 'Helicopter',
    texItliano: 'Elicottero',
    audio: 'Audies/Transsport_words/15_elicottero.mp3',
  ),
  model(
    image: 'assets/Images/transport_icons/transport/16_rocket.png',
    textenglish: 'Rocket',
    texItliano: 'Razzo',
    audio: 'Audies/Transsport_words/16_razzo.mp3',
  ),
  model(
    image: 'assets/Images/transport_icons/transport/17_boat.png',
    textenglish: 'Boat',
    texItliano: 'Barca',
    audio: 'Audies/Transsport_words/17_barca.mp3',
  ),
  model(
    image: 'assets/Images/transport_icons/transport/18_ship.png',
    textenglish: 'Ship',
    texItliano: 'Nave',
    audio: 'Audies/Transsport_words/18_nave.mp3',
  ),
  model(
    image: 'assets/Images/transport_icons/transport/19_ferry.png',
    textenglish: 'Ferry',
    texItliano: 'Traghetto',
    audio: 'Audies/Transsport_words/19_traghetto.mp3',
  ),
  model(
    image: 'assets/Images/transport_icons/transport/20_scooter.png',
    textenglish: 'Scooter',
    texItliano: 'Scooter',
    audio: '',
  ),
  model(
    image: 'assets/Images/transport_icons/transport/21_traffic_light.png',
    textenglish: 'Traffic Light',
    texItliano: 'Semaforo',
    audio: 'Audies/Transsport_words/20_semaforo.mp3',
  ),
  model(
    image: 'assets/Images/transport_icons/transport/22_fuel_pump.png',
    textenglish: 'Fuel Pump',
    texItliano: 'Pompa di benzina',
    audio: 'Audies/Transsport_words/21_pompa_di_benzina.mp3',
  ),
  model(
    image: 'assets/Images/transport_icons/transport/23_road.png',
    textenglish: 'Road',
    texItliano: 'Strada',
    audio: 'Audies/Transsport_words/22_strada.mp3',
  ),
  model(
    image: 'assets/Images/transport_icons/transport/24_anchor.png',
    textenglish: 'Anchor',
    texItliano: 'Ancora',
    audio: 'Audies/Transsport_words/23_ancora.mp3',
  ),
  model(
    image: 'assets/Images/transport_icons/transport/25_suitcase.png',
    textenglish: 'Suitcase',
    texItliano: 'Valigia',
    audio: 'Audies/Transsport_words/24_valigia.mp3',
  ),
  model(
    image: 'assets/Images/transport_icons/transport/26_map.png',
    textenglish: 'Map',
    texItliano: 'Mappa',
    audio: 'Audies/Transsport_words/25_mappa.mp3',
  ),
  model(
    image: 'assets/Images/transport_icons/transport/27_compass.png',
    textenglish: 'Compass',
    texItliano: 'Bussola',
    audio: 'Audies/Transsport_words/26_bussola.mp3',
  ),
  model(
    image: 'assets/Images/transport_icons/transport/28_parachute.png',
    textenglish: 'Parachute',
    texItliano: 'Paracadute',
    audio: 'Audies/Transsport_words/27_paracadute.mp3',
  ),
];
